Learn-Build-Teach/deals-for-devs

src/components/Nav.tsx
I just noticed that the navbar contained an anchor tag. I replaced it with the Next.js Link component for client side routing
=> Change anchor tag to Link component

src/components/subscriber/Subscriber.tsx, src/lib/queries.ts, src/types/Types.ts
closes #16 
Added Status enum:
```ts
export enum Status {
SUBSCRIBED = 'subscribed',
UNSUBSCRIBED = 'unsubscribed',
}
```
implemented in the following files:
- Types.ts
- Subscriber.tsx
- queries.ts
=> feat: closes #16 - add subscription status enum

src/app/layout.tsx, src/components/Hero.tsx, tailwind.config.ts
This fixes issue #10 
Sorry for the delay, I've been sick for a few days now 😢. 
I ended up editing the layout for md and lg, here's how it looks on my computer:
md:
lg:
Please let me know if that looks ok to you or if I should change anything else, I also noticed on the smallest view the <p> text seems a bit long since it is much wider than the email input, so if you want me to I could add a max width?
=> Make md and lg views of hero responsive

src/app/deals/add/DealForm.tsx, src/components/Footer.tsx, src/components/nav/Nav.tsx
This PR makes the code more a11y-friendly, making it easier for developers who use screen readers to navigate the website. 
Closes #62
=> feat: add aria-label to input

src/actions/deals.ts, src/actions/subscriber-subscribe.ts
Solves Issue #4 
I believe this is what was being asked for but please let me know if there is more or different ways we are wanting to handle things with using `.safeParse` for Zod instead of `.parse`.
=> feat: added logic to use safeparse instead of parse

src/app/(deals)/deals/[category]/page.tsx, src/components/CategoryOption.tsx, src/components/CategoryOptions.tsx, src/components/DealGradientPlaceholder.tsx, src/components/deals/DealCard.tsx, src/components/forms/add-a-deal/CategorySelect.tsx, src/components/forms/add-a-deal/ReviewDeal.tsx, src/lib/queries.ts, src/types/Types.ts
This adds default "images" for deals that display a gradient based on the category type along with an icon.
Closes #130
=> feat: Add Default Image for Deals

src/components/forms/add-a-deal/DragAndDropImage.tsx, src/components/forms/add-a-deal/ProductInfo.tsx
Show error message and handle error when uploading an image that is too big
=> fix: handle error for too large file upload

prisma/schema.prisma
coverImageId should not be unique. This allows for null or empty string
=> Fix: no unique constraint coverImageId

prisma/schema.prisma
Removing unnecessary id property on subscriber table since xata_id exists
=> Fix: Remove ID From Subscriber

src/app/deals/add/layout.tsx, src/app/layout.tsx
This changed is to remove padding in mobile view to allow more content width.
[](https://github.com/Learn-Build-Teach/deals-for-devs/issues/138)
** BEFORE CHANGES **
** AFTER CHANGES **
- [x ] If this PR addresses an open Issue, it is linked in the `Issue` section
=> chore: changed default px to px-2

src/components/forms/add-a-deal/DragAndDropImage.tsx, src/components/forms/add-a-deal/ProductInfo.tsx
Add a requirement of 16 by 9 for deal images to keep a consistent aspect ratio
Closes #175 
https://github.com/Learn-Build-Teach/deals-for-devs/assets/5391915/b4e0ef39-2869-4f0e-9091-759b2bc71a5f
=> feat: add 16 x 9 image ratio requirement to form

README.md
Implements a simpler way to display contributors. Originally shared by @joshmedeski.
=> feat: added contributor rocks link on readme

src/components/Overlay.tsx, src/components/search/GlobalSearch.tsx, src/components/search/SearchResults.tsx
This PR updates the overlay component to use the native html `<dialog>` element. It also adds accessible names to the buttons within the overlay and announces to screen reader users when there are no search results.
Closes #229
=> Fix: make overlay accessible

src/app/deals/[id]/loading.tsx, src/app/deals/[id]/page.tsx, src/app/deals/category/[category]/page.tsx, src/app/deals/page.tsx, src/app/page.tsx, src/components/IconButton.tsx, src/components/deals/ApprovedDeals.tsx, src/components/deals/ApprovedDealsByCategory.tsx, src/components/deals/DealCard.tsx, src/components/deals/DealGradientPlaceholder.tsx, src/components/deals/DealImage.tsx, src/components/deals/DealPreview.tsx, src/components/deals/DealsList.tsx, src/components/deals/FeaturedDeals.tsx, src/components/deals/FeaturedDealsSection.tsx, src/components/deals/loading/LoadingDealImage.tsx, src/components/deals/loading/LoadingDealsList.tsx, src/components/deals/loading/LoadingPreview.tsx, src/components/search/SearchedDeal.tsx
This PR adds loading states for deal pages to improve the time to first byte (TTFB)
Performance metrics for deals pages were showing up as poor in the Sentry dashboard. This was because the time to first byte (TTFB) was slow. This was caused by not providing loading states for asynchronously loaded data.
=> PERF: Improve Time to First Byte For Deals Pages

src/components/forms/DatePicker.tsx, src/components/forms/add-a-deal/CouponDetails.tsx
React DayPicker has a prop to disable dates based on a match. I set the passed dates of the start date picker to be disabled. As for the end date picker I have the disabled dates based on the start date.
https://github.com/Learn-Build-Teach/deals-for-devs/issues/177
https://github.com/user-attachments/assets/2f06ccf6-f56b-49ba-9531-312a041eeed6
- [x ] The `Description` gives a good representation of the changes made
- [ x] If this PR addresses an open Issue, it is linked in the `Issue` …
=> Fix:  end dates before start

src/app/(admin)/dashboard/actions.ts, src/app/(admin)/sign-in/[[...sign-in]]/page.tsx, src/app/(admin)/sign-up/[[...sign-up]]/page.tsx, src/components/dashboard/ApproveDealButton.tsx, src/components/dashboard/DeleteDealButton.tsx, src/env.ts, src/middleware.ts
Updated links an default variables to get rid of `/admin` in path.
=> fix: update dashboard routes to remove admin

prisma/schema.prisma, src/actions/dashboard/adminUser.ts, src/actions/dashboard/subscriber.ts, src/app/(admin)/dashboard/actions.ts, src/app/(admin)/dashboard/admins/page.tsx, src/app/(admin)/dashboard/layout.tsx, src/app/(admin)/dashboard/subscribers/page.tsx, src/app/(public-pages)/deals/add/schemas.tsx, src/components/dashboard/AdminNav.tsx, src/components/dashboard/SubmitButton.tsx, src/components/dashboard/admin/AdminList.tsx, src/components/dashboard/admin/DeleteButton.tsx, src/components/dashboard/admin/NewAdminForm.tsx, src/components/dashboard/subscribers/NewSubscriberForm.tsx, src/components/subscriber/SubscriberList.tsx, src/lib/queries.ts, src/queries/adminUsers.ts, src/types/Types.ts, src/utils/auth.ts
Add admin features to manage admin
- updated DB schema to use `xata_id` as primary key for `AdminUser` table
- added `email` property to `AdminUser` table
- added dashboard page for managing admins
- created new admin form
- created admin list with delete functionality using server actions
- refactored subscriber dashboard page to match admin page (more design work to come)
https://github.com/user-attachments/assets/e7d1f722-b5a2-4f27-bec7-8ac89f6687c2
=> FEAT: Managing Admin Capabilities

src/components/deals/DealDetails.tsx
Don't display coupon percent unless it is greater than 0
=> fix: dont display coupon percent unless greater than 0

src/app/(admin)/dashboard/deals/[id]/edit/page.tsx, src/app/(admin)/dashboard/deals/[id]/page.tsx, src/app/(public-pages)/deals/[id]/page.tsx, src/components/dashboard/AdminDealsList.tsx, src/components/dashboard/DashboardPage.tsx, src/components/deals/DealDetails.tsx
- move dashboard deal edit route to `/dashboard/deals/[id]/edit`
- add dashboard deal details page at `/dashboard/deals/[id]`
- remove unnecessary metadata generation
- use `Section` component for dashboard pages
https://github.com/user-attachments/assets/44417196-3e12-4fab-a719-73bed5fbb9fd
=> FEAT: reorganize admin deal edit route

src/components/deals/loading/LoadingPreview.tsx, src/components/deals/loading/LoadingTag.tsx, src/components/deals/loading/LoadingTagsList.tsx, src/components/deals/loading/LoadingText.tsx
Update loading states for deal details to match the `DealDetails.tsx` component
- added `LoadingText` component with properties for width and style
- added loading components for Tags
Closes #248 
https://github.com/user-attachments/assets/271b9ad6-c391-4ff0-b8cf-f1b8ba437f07
=> fix(loading): match loading states with deal details

src/components/Overlay.tsx, src/components/search/GlobalSearch.tsx
Search overlay failed to open a second time (after closing once)
- overlays handles `esc` key press and calls `onClose` function
- remove `esc` key handler in `GlobalSearch`
- move body overflow styles to `Overlay` so there is not scroll any time it is used
Closes #250 
https://github.com/user-attachments/assets/7e10a5d2-3d12-4e7f-a454-6f4bf8767a77
=> fix: overlay opens and closes appropritately

src/app/(public-pages)/deals/category/[category]/layout.tsx, src/app/(public-pages)/deals/category/[category]/page.tsx, src/app/(public-pages)/deals/page.tsx, src/components/CategoryOption.tsx, src/components/CategoryOptions.tsx, src/components/deals/ApprovedDealsByCategory.tsx, src/lib/queries.ts
Show number of deals by category and don't show category options that don't have any deals.
=> feat: added category counts to category options

src/components/deals/details/DealDetails.tsx
Deal details page was missing the discount overlay on the deal image because the `couponPercent` prop was not being  passed.
Added the `couponPercent` prop to the `DealDetails` component.
=> fix: display discount on deal details

src/components/ui/calendar.tsx
Make sure calendar buttons are visible by removing button variant.
https://github.com/user-attachments/assets/a9a98a03-7eac-4e5f-b1e0-3e0a79d3b544
=> fix: remove button variant from calendar

.gitignore, .husky/commit-msg, pnpm-lock.yaml
Solving  #207 
Just changed the `.husky/commit-msg`  form:
```
npm run lint-commit
```
to this:
```  
#!/bin/sh
npx --no-install commitlint --edit $1
```
This works across all platforms as I'm telling it to run the command in ` sh ` .
In windows:
` npm ` or ` npx ` doesn't treat ` $1 ` as shell script in package.json format:
```
"lint-commit": "npx --no-install commitlint --edit "$1"",
```
this was the problem
As `$git add * ` ignores `.husky/commit-msg` I had to do `$git add . `  which will also add the `.env`  file. So I added ` .env ` to the `.gitignore` file. For my machine(win 10) the ` .env*.local `  was ignored when doing ` $git add . ` and added `.env` to git tracking
- [ X ] I have carefully read through and understand the [Deals-for-Devs Contributing …
=> fix: commitlint blocking commits in windows 
