Learn-Build-Teach/deals-for-devs

package.json

chore: update Sentry package

---

.environment.d.ts
sentry.client.config.ts
sentry.edge.config.ts
sentry.server.config.ts

Chore move sentry dsn to an environment variable

---

src/actions/subscriber-subscribe.ts

Chore email character case checking upper lower

---

src/components/forms/SubscribeForm.tsx
src/components/forms/SubscribeFormButton.tsx

closes #14 
Added a circle animation that animates in a circle while the subscribe form is processing.  While the subscribe form is processing the submit button is disabled.
https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/6f609199-2c47-4206-92da-621827f539f4

feat: closes #14 - add circle animation to subscribe form

---

README.md

The README now contains basic instructions on how to start a local dev environment with additional sections for tech stack and contributions.
Fixes #36

docs: project readme.md

---

.vscode/settings.json
next.config.js

- fix(footer): sentry and clerk links
- docs: update README.md [skip ci]
- docs: create .all-contributorsrc [skip ci]
- docs: add chris-nowicki as a contributor for code (#46)
- chore: update sentry project id

fix update sentry project

---

.github/pull_request_template.md

This PR adds a template to help contributors describe their pull requests
Closes #60

feat: add template for pull requests

---

src/app/page.tsx
src/components/Hero.tsx
src/components/NeverMissADeal.tsx
src/components/nav/Nav.tsx

Added components back into the landing page:
- Navbar
- Never Miss a Deal
- Give Aways
https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/83d181f7-d30b-49b2-81cf-d111705f34bd

Feat add back landing page sections

---

.github/pull_request_template.md

This PR cleans up and added some additional information to the PR-template within the .github folder.
Closes: #83

docs: updated and re-structured pull_request_template

---

.github/contributing.md

This PR includes a brief statement that also gives a direct link to the figma file for contributors to have for reference.
This PR does not close any specific issue.

docs: included a link to the figma file

---

README.md

After adding a contribution guide at `.github/contributing.md`, we need to make that more accessible by adding a reference to it in the project's root `README.md`.
Closes #96

docs(readme): added link to contribution guide

---

.github/contributing.md

Added a Figma file link to the contributing doc so contributors can reference the design.
This PR does not close any specific issue.

docs: added figma file link

---

src/app/deals/[category]/page.tsx
src/app/deals/page.tsx
src/components/deals/Deal.tsx
src/components/deals/DealsList.tsx
src/components/deals/FeaturedDeals.tsx

Instead of loading components on the client unnecessarily, we should load them on the server

fix: removed unnecessary use client

---

README.md

Improve onboarding documentation for setting up Xata db and Prisma.

Docs xata onboarding

---

src/app/(deals)/deals/add/layout.tsx
src/app/(deals)/deals/page.tsx
src/app/layout.tsx
src/components/CategoryOptions.tsx
src/components/Footer.tsx
src/components/NeverMissADeal.tsx
src/components/PageHeader.tsx
src/components/deals/DealCard.tsx
src/components/deals/DealsList.tsx
tailwind.config.ts

Update deal cards based on Figma design.
Closes #117 
Where do we link people when they click the card? Right now, the cards are missing some details (dates, coupon details, etc.) We need to address this in a future issue.

Feat update card design

---

package-lock.json
src/app/(subscriber)/confirm/page.tsx
src/app/api/validate/route.ts

- Removed redirect to subscriber preferences page after confirming email.
- user now redirects to a page that says their subscription is successful
closes #124
https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/621850fd-a7b1-42bb-be34-a17a16bcdb93

Feature: remove redirect to preferences page

---

prisma/schema.prisma
src/app/api/validate/route.ts
src/components/subscriber/Subscriber.tsx
src/lib/queries.ts

Remove `id` property from subscriber in lieu of `xata_id` property.

fix: remove subscriber id

---

src/app/deals/category/[category]/page.tsx
src/app/deals/page.tsx
src/components/CategoryOption.tsx
src/components/CategoryOptions.tsx

Added styles for the currently selected category by inspecting the url path
Closes #133

Feat: Styles for currently selected category

---

prisma/schema.prisma
src/components/forms/add-a-deal/ReviewDeal.tsx

Change description to text field in Prisma schema
`  description    String     @db.Text`

fix: convert description field to text

---

src/components/deals/DealCard.tsx
src/components/deals/DealImage.tsx
src/components/search/SearchedDeal.tsx

Created reusable component for deal images

feat: created deal image component

---

src/app/api/deals/route.tsx
src/components/DealPreview.tsx

hacked search records to match expected format with xata_id

Fix search record id

---

src/components/DealGradientPlaceholder.tsx
src/components/deals/DealImage.tsx

Add borders to deal images so they stand out a bit on the dark background.
closes #164 

Feat image outlines

---

package-lock.json
package.json
src/app/layout.tsx

Add plausible script to head for analytics tracking

Add plausible analytics

---

prisma/schema.prisma
src/components/deals/DealCard.tsx

Update prisma schema to support null end date
```  endDate        DateTime?  @db.Date```
- [x ] If this PR addresses an open Issue, it is linked in the `Issue` section

fix: prisma schema to support null end date

---

prisma/schema.prisma

Dev to Staging

---

src/components/DealPreview.tsx
src/components/DevGiveaways.tsx
src/components/NeverMissADeal.tsx

1. Fixed typo in "Dev Giveaways"
2. Added `margin-bottom` to `NeverMissADeal` component
3. Made `NeverMissADeal` component more responsive
4. Updated `DealPreview` component to show whitespace and line breaks.
Closes #179 
Closes #180 
Closes #181 
Closes #183

fix(UI/UX): fixed several UX issues for MVP 1

---

src/app/deals/[id]/page.tsx
src/app/deals/category/[category]/page.tsx
src/app/deals/page.tsx
src/app/page.tsx

Add revalidate to each deal page to break cache.
- [x ] If this PR addresses an open Issue, it is linked in the `Issue` section

fix: add revalidate to deals pages

---

src/app/deals/[id]/page.tsx

Feat: Add OG Image deals page

---

src/lib/queries.ts

Fixed bug that allowed expired deals to be shown
Closes or Relates to: #202

Bug dont show outdated deals

---

src/app/disclaimer/page.tsx

Adds a Disclaimer route and page to the project for potential future use on the footer. 
Closes or Relates to: #200

feat: added disclaimer route and page with placeholder for text

---

src/components/forms/add-a-deal/ContactInfo.tsx
src/components/forms/add-a-deal/CouponDetails.tsx
src/components/forms/add-a-deal/ProductInfo.tsx
src/components/forms/add-a-deal/ReviewDeal.tsx

Updated the button colors for the add-a-deal sections 
Closes or Relates to: #188

fix: updated the button color to be brighter

---

src/app/(subscriber)/preferences/page.tsx
src/app/admin/sign-in/[[...sign-in]]/page.tsx
src/app/admin/sign-up/[[...sign-up]]/page.tsx
src/app/deals/[id]/not-found.tsx
src/app/deals/[id]/page.tsx
src/app/deals/add/layout.tsx
src/app/deals/category/[category]/page.tsx
src/app/deals/page.tsx

Many of the pages were missing `<main>` landmark elements so I updated the outermost `<div>` to be a `<main>` for the pages where it was needed.

fix: add main landmark to pages

---

.env.example
README.md

Added more clarity to environment variables with better examples.
Closes #215 

docs: clarify environment variables in example env file and readme

---

src/components/forms/add-a-deal/Input.tsx
src/components/forms/add-a-deal/ProductInfo.tsx
src/components/forms/add-a-deal/ReviewDeal.tsx

Added extra validation for submitted link for deals to ensure it includes `https://` prefix
Closes #189 
- [x ] The `Description` gives a good representation of the changes made
- [x ] If this PR addresses an open Issue, it is linked in the `Issue` section

Bug no link validation

---

src/app/api/deals/route.tsx

Added filter to search API to ensure only approved deals are searchable
Closes #213 
- [x ] The title of this PR follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format

Bug filter unapproved deals in search

---

src/app/deals/[id]/page.tsx
src/app/deals/add/actions.tsx
src/app/deals/add/product-info/ImageUpload.tsx
src/app/deals/add/schemas.tsx
src/app/deals/add/types.ts
src/components/ClickableCouponCode.tsx
src/components/DealPreview.tsx
src/components/FeaturedDeals.tsx
src/components/forms/add-a-deal/CategorySelect.tsx
src/components/forms/add-a-deal/ContactInfo.tsx
src/components/forms/add-a-deal/CouponDetails.tsx
src/components/forms/add-a-deal/Input.tsx
src/components/forms/add-a-deal/ProductInfo.tsx
src/components/forms/add-a-deal/ReviewDeal.tsx
src/components/forms/add-a-deal/TextArea.tsx
src/context/AddDealContext.tsx

- real-time validation on individual inputs that only show up after the input has been blurred
- validation on submission of each page on the server
- validation on the server from review page submission that redirects the user to appropriate page if one is invalid, and triggers that page to validate immediately by passing the `?validate=true` query parameter
Closes #221 
CleanShot 2024-07-09 at 10.16.16.mp4
- [ x] If …

Feat: Deal Form Validation

---

src/components/forms/add-a-deal/CategorySelect.tsx

Updated the select combobox to use a label instead of span, and added an aria-label to the trigger.

fix: update semantics of combobox

---

src/app/deals/[id]/page.tsx

This PR uses the getStaticProps using ISR to allow the data from the db to be cahched as well as make sure to improve performance overall
Closes or Relates to: #194

feat: added generateStaticParams to use ISR with the dynamic route for deals

---

src/app/deals/[id]/loading.tsx
src/app/deals/[id]/page.tsx
src/app/deals/category/[category]/page.tsx
src/app/deals/page.tsx
src/app/page.tsx
src/components/IconButton.tsx
src/components/Overlay.tsx
src/components/deals/ApprovedDeals.tsx
src/components/deals/ApprovedDealsByCategory.tsx
src/components/deals/DealCard.tsx
src/components/deals/DealGradientPlaceholder.tsx
src/components/deals/DealImage.tsx
src/components/deals/DealPreview.tsx
src/components/deals/DealsList.tsx
src/components/deals/FeaturedDeals.tsx
src/components/deals/FeaturedDealsSection.tsx
src/components/deals/loading/LoadingDealImage.tsx
src/components/deals/loading/LoadingDealsList.tsx
src/components/deals/loading/LoadingPreview.tsx
src/components/forms/add-a-deal/Input.tsx
src/components/forms/add-a-deal/ProductInfo.tsx
src/components/forms/add-a-deal/ReviewDeal.tsx
src/components/search/GlobalSearch.tsx
src/components/search/SearchResults.tsx
src/components/search/SearchedDeal.tsx

Merge features from dev to staging
- statically generated pages for individual deal
- add loading states to improve performance with streaming
- accessibility issues

Merge From Dev

---

src/app/deals/[id]/page.tsx
src/components/ClickableCouponCode.tsx
src/components/deals/DealPreview.tsx
src/components/forms/add-a-deal/ReviewDeal.tsx
src/components/forms/add-a-deal/StepNavigation.tsx
src/components/forms/add-a-deal/Tag.tsx
src/lib/queries.ts
src/types/Types.ts

- updated deal preview design to be more responsive
- include tags
- add min width to sidebar navigation in form

style: update deal preview

---

.github/contributing.md
.github/setup.md

Updated contributing docs to submit PRs to main branch

docs: Send PRs to main

---

prisma/schema.prisma
src/app/api/tracking/route.ts
src/components/deals/DealDetails.tsx
src/lib/queries.ts

Add support for tracking link clicks.
https://github.com/user-attachments/assets/6262beae-b784-4f2e-b432-7adb2e753db2

feat: add tracking for link clicks

---

src/app/(public-pages)/deals/add/DealForm.tsx
src/app/(public-pages)/deals/add/schemas.tsx
src/components/ClickableCouponCode.tsx
src/components/dashboard/AdminDealsList.tsx
src/components/deals/DealCard.tsx
src/components/deals/DealDetails.tsx
src/components/deals/DealImage.tsx
src/components/search/SearchedDeal.tsx

Ensure discounts are displayed on all cover images and details pages.

BUG: Discount not displayed on images

---

src/components/deals/FeaturedDealsSection.tsx

fix: add limit to featured deals

---

src/app/(public-pages)/(subscriber)/confirm/page.tsx
src/app/(public-pages)/(subscriber)/preferences/page.tsx
src/app/(public-pages)/deals/add/layout.tsx
src/app/(public-pages)/deals/add/page.tsx
src/app/(public-pages)/deals/category/[category]/page.tsx
src/app/(public-pages)/deals/page.tsx
src/app/(public-pages)/disclaimer/page.tsx
src/app/(public-pages)/layout.tsx
src/app/(public-pages)/page.tsx
src/components/Container.tsx
src/components/PageHeader.tsx
src/components/Section.tsx
src/components/deals/DealDetails.tsx
src/components/nav/Nav.tsx
src/components/subscriber/VerifiedStatus.tsx

- `Section` and `Layout` components to be reused across all pages
- Update deal details with overlayed image and white section

feat(design): Update Deal Details Page

---

src/app/(public-pages)/deals/[id]/not-found.tsx

Styling on 404 page was off because it was not wrapped in a `Container` component.

fix: add container to 404

---

src/app/(admin)/dashboard/FeaturedDeals.tsx
src/app/(admin)/dashboard/page.tsx
src/app/(admin)/dashboard/subscribers/page.tsx
src/components/dashboard/DashboardCard.tsx
src/components/subscriber/SubscriberList.tsx
src/queries/subscribers.ts

- update dashboard to sections for subscirbers and featured deals
- add link props to dashboard card
- update queries for subscribers and featuerd deals to include limit

Feat_add_sections_to_dashboard

---

src/app/(admin)/dashboard/actions.ts
src/app/(public-pages)/deals/[id]/page.tsx
src/app/(public-pages)/deals/category/[category]/page.tsx
src/app/(public-pages)/deals/page.tsx
src/app/(public-pages)/disclaimer/page.tsx
src/app/(public-pages)/page.tsx

feat: removed revalidate times and added manual calls to revalidatePath

---

prisma/schema.prisma

Add cascade rules to DealView to delete them when deal is deleted

fix: add cascade rules to DealView to delete them when deal is deleted

---

src/app/(public-pages)/deals/add/DealForm.tsx

The query was fine. it was just the "DealForm.tsx"
> It was missing the `<input/>` tag for "endDate"
After fixing that everything works form my end. Form `main` branch.
Issue #257 
I tryed to change the "endDate" in xata to see the deals and it was working.
Please let me know if there's any problem

fix: old deals still showing on All deals page
